name: update submodules

on:
  push:
    branches:
      - scripts
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Update submodules in main
        run: |
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
          gh auth setup-git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://github.com/m-c-frank/justthoughts
          cd justthoughts
          git submodule update --init --recursive
          cd scripts
          git checkout scripts
          git fetch
          git pull
          cd ..
          git add .
          git add .
          git commit -m "Updated scripts submodule to latest commit"
          git push origin main
